services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autos
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      retries: 20

  api:
    build:
      context: ./api
    volumes:
      - ./api:/src
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/autos?sslmode=disable
    ports: ["8787:8787"]
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
      # - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8787
    ports: ["5173:5173"]
    depends_on: [ api ]
